### ISSUE TITLE
Icon stays black when using Dark Mode menubar in OSX

### ISSUE THREAD

**Issue by ptbrowne** [nschum/Gitifier#54]
I am using DarkMode in OSX 10.10 and the menu icon is invisible.

I guess the fix should be similar to 

https://github.com/owncloud/client/commit/01a72121049a103727b47cb0bde2db2d4d311b88

Sorry not to make a pull request but I know nothing at building MacOSX apps...

**Comment by mackuba** [comment]
Are you using the latest version? I've already fixed this: https://github.com/nschum/Gitifier/issues/52.

**Comment by ptbrowne** [comment]
Works perfectly now. Thanks !

**Comment by ptbrowne** [comment]
1 minor problem though. The icon is not retina:
![screen shot 2015-02-06 at 16 51 37](https://cloud.githubusercontent.com/assets/465582/6082270/6ff451b8-ae20-11e4-8191-7e3d645abac4.png)

**Comment by mackuba** [comment]
Hmm, I don't have a Retina MacBook, but I did update the icon with a Retina version and I've tested it in a HiDPI mode on my iMac and it looked good:

![screen shot 2015-02-13 at 13 40 01](https://cloud.githubusercontent.com/assets/28465/6187379/01ffd6c6-b386-11e4-8655-0bfdd617aa2c.png)

@nschum do you have any Retina Macs?

**Comment by nschum** [comment]
Just got a Retina MacBook a few days ago. Looking good here.

@ptbrowne Anything unusual about your setup? Do you maybe have an external displays or something like that?
